#  make admin username static
#$ export ADMIN_INIT_USERNAME=admin
#  make password deterministic (based on release name)
#$ export ADMIN_INIT_PASSWORD=$RELEASE_NAME-$(echo $RELEASE_NAME | md5sum | cut -c 1-8)

#$ if echo $RELEASE_NAME | grep -Eqs 'dev$'; then
#$   export REPLICAS=1
#$ else
#$   export REPLICAS=3
#$ fi
#$ 
#$ 

replicaCount: $REPLICAS  --kush-interpolate
