apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-interpolation-example
spec:
  template:
    spec:
      containers:
        - name: interpolation-example
          env:
            - name: ADMIN_PASSWORD
              value: $ADMIN_INIT_PASSWORD        --kush-interpolate
            - name: ADMIN_USERNAME
              value: $ADMIN_INIT_USERNAME        --kush-interpolate
